main:
  - identifier: nav.posts
    pageRef: posts
    weight: 10
    params:
      icon: blog
  - identifier: nav.legacy
    pageRef: legacy
    weight: 11
    params:
      icon: folder
  - identifier: nav.categories
    pageRef: /categories
    weight: 30
    params:
      icon: categories
  - identifier: nav.tags
    pageRef: /tags
    weight: 40
    params:
      icon: tags
  - identifier: nav.archives
    pageRef: /archives
    weight: 50
    params:
      icon: archive

footer:
  - identifier: nav.about
    pageRef: /about
    weight: 10
    params:
      icon: about
  - identifier: nav.contact
    url: mailto:notatnik@domowy.top
    weight: 20
    params:
      icon: contact
  - identifier: nav.rss
    url: /index.xml
    weight: 30
    params:
      icon: rss

social:
  - name: GitHub
    url: https://github.com/Fisiu
    weight: 10
    params:
      icon: github
  # - name: Twitter
  #   url: https://twitter.com/username
  #   weight: 20
  #   params:
  #     icon: twitter
  - name: LinkedIn
    url: https://linkedin.com/in/mariuszfik
    weight: 30
    params:
      icon: linkedin
  - name: Email
    url: mailto:notatnik@domowy.top
    weight: 40
    params:
      icon: email
